language: generic
global:
  - CLIVERSION=0.7.2
matrix:
  include:
    - env:
        - BOARD="Seeeduino:samd:zero"
    - env:
        - BOARD="Seeeduino:samd:seeed_wio_terminal"

before_install:
  - sudo apt-get install --reinstall python3-pip
  - python3 -m pip install
  - wget https://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz
  - tar zxvf setuptools-0.6c11.tar.gz
  - cd setuptools-0.6c11
  - python3 setup.py install
  - cd ~
  - git clone https://github.com/Seeed-Studio/ardupy-aip
  - pip3 install pip
  - cd ardupy-aip
  - ls
install:
  - pip3 install -U -e .
  - aip

script: 
  - echo "CI Test"
  - aip install  Seeed-Studio/seeed-ardupy-my9221
  - aip build 
  
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
