language: generic
global:
  - CLIVERSION=0.7.2
matrix:
  include:
    - env:
        - BOARD="Seeeduino:samd:zero"
    - env:
        - BOARD="Seeeduino:samd:seeed_wio_terminal"

before_install:
  - git clone https://github.com/Seeed-Studio/ardupy-aip
  - cd ardupy-aip
install:
  - pip3 install -U -e .
  - aip help

script: 
  - echo "CI Test"
  - aip install  Seeed-Studio/seeed-ardupy-my9221
  - aip build 
  
notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
